const content = {
    en: {
        "nav-home": "Home",
        "nav-method": "Methodology",
        "nav-download": "Download",
        "nav-docs": "Docs",
        "nav-results": "Results",
        "hero-kicker": "Optical Music Recognition",
        "hero-title": "A Python toolkit for sheet music recognition.",
        "hero-lead": "PyClef detects musical symbols in score images and applies MIRP, a staff-referenced inference method, to reconstruct note pitch and export reviewable outputs.",
        "hero-start": "Get started",
        "hero-download": "Download Windows",
        "hero-method": "Read the methodology",
        "metric-classes": "symbol classes",
        "metric-pitch": "TRA with MIRP",
        "intro-kicker": "Overview",
        "intro-title": "Object detection alone is not enough for OMR.",
        "intro-text": "PyClef treats detection as one stage of a larger reconstruction pipeline. The detector locates symbols; MIRP uses the detected clef and staff geometry to infer pitch from relative vertical displacement.",
        "card-neural-title": "Detection model",
        "card-neural-text": "The current model uses YOLOv11S trained on 208 DeepScoresV2 Dense classes, with 0.4126 mAP@[0.5:0.95] in the reported evaluation.",
        "card-mirp-title": "MIRP",
        "card-mirp-text": "The Staff-Referenced Musical Inference Method defines a reference note from the clef and staff, then infers the pitch of detected notes.",
        "pipeline-kicker": "Workflow",
        "pipeline-title": "The processing pipeline is explicit and auditable.",
        "step-detect-title": "Detect",
        "step-detect-text": "Load a PDF or image and detect staves, clefs, notes, rests and related notation symbols.",
        "step-refine-title": "Infer",
        "step-refine-text": "Use MIRP to convert staff-relative geometry into note names and octaves.",
        "step-reconstruct-title": "Review",
        "step-reconstruct-text": "Create annotated pages so the recognition result can be inspected visually.",
        "step-export-title": "Export",
        "step-export-text": "Write MIDI, MP3 and synchronized video files when those outputs are selected.",
        "app-kicker": "Desktop application",
        "app-title": "A focused interface for running PyClef locally.",
        "app-text": "Select a score, choose the desired outputs, set the BPM and run the pipeline. Results are written to a folder named after the input file.",
        "app-f1": "PDF, PNG and JPG input",
        "app-f2": "Annotated score pages",
        "app-f3": "MIDI, MP3 and synchronized video",
        "app-f4": "Integrated MIDI player with waterfall preview",
        "paper-kicker": "Paper",
        "paper-title": "Methodology and evaluation.",
        "paper-text": "The article describes the PyClef pipeline, the MIRP method and the reported detection and pitch reconstruction results.",
        "paper-download": "Coming soon",
        "home-download-setup": "Download setup",
        "paper-method": "Methodology",
        "method-kicker": "Methodology",
        "method-title": "MIRP: Staff-Referenced Musical Inference.",
        "method-lead": "MIRP uses the detected clef and staff boundaries to define a reference note. Other notes are inferred from their vertical displacement relative to that reference.",
        "mirp-1-title": "Staff reference",
        "mirp-1-text": "The detected staff provides its upper and lower boundaries. The vertical step is estimated from these coordinates.",
        "mirp-2-title": "Clef reference",
        "mirp-2-text": "The clef determines the reference note used to interpret positions on the staff.",
        "mirp-3-title": "Pitch reconstruction",
        "mirp-3-text": "In the reported YOLOv11S experiment, TRA improved from 0.04 to 0.975 after MIRP.",
        "method-flow-kicker": "Algorithm",
        "method-flow-title": "MIRP is applied after object detection.",
        "flow-1-title": "Collect detections",
        "flow-1-text": "Separate structural detections, such as staves and clefs, from note detections.",
        "flow-2-title": "Estimate staff step",
        "flow-2-text": "Compute the distance between adjacent staff positions from the detected staff box.",
        "flow-3-title": "Infer pitch",
        "flow-3-text": "Measure the vertical displacement between the reference note and each detected note center.",
        "flow-4-title": "Export results",
        "flow-4-text": "Write annotated images and optional playback files for inspection and reuse.",
        "article-kicker": "Article",
        "article-title": "PyClef: Optical Music Recognition with MIRP.",
        "article-text": "The paper reports YOLOv11S results on DeepScoresV2 Dense and shows that MIRP raises pitch reconstruction from about 4% to 97.5%.",
        "docs-kicker": "Documentation",
        "docs-title": "Install, run and inspect PyClef outputs.",
        "docs-lead": "PyClef can be used as a Windows desktop app or from Python. This guide covers installation, processing options, generated files, MIDI playback and review tools.",
        "docs-download-cta": "Download options",
        "docs-python-cta": "Install with pip",
        "download-kicker": "Windows installer",
        "download-title": "Download the PyClef setup and test it now on your Windows computer.",
        "download-text": "Use the setup when you want the fastest way to open the desktop app and process a score locally.",
        "download-button": "Download setup",
        "download-release": "Open release",
        "download-note": "Recommended for Windows users who want the desktop experience.",
        "download-page-kicker": "Download",
        "download-page-title": "Choose how you want to run PyClef.",
        "download-page-lead": "Use the Windows setup for the quickest desktop test, or install the Python package when you want the API and command-line workflow.",
        "download-windows-kicker": "Windows setup",
        "download-windows-title": "Download PyClef and test it now on your Windows computer.",
        "download-windows-text": "Recommended if you want the desktop interface without preparing a Python environment first.",
        "download-windows-button": "Download Windows setup",
        "download-windows-note": "The installer is distributed through GitHub Releases because it is a large file.",
        "download-python-kicker": "Python package",
        "download-python-title": "Install PyClef from PyPI.",
        "download-python-text": "Use this path when you want to call PyClef from scripts, notebooks or a terminal.",
        "download-python-button": "Open Python guide",
        "download-steps-kicker": "Next steps",
        "download-steps-title": "After installation, open a score and generate your first outputs.",
        "download-step-1-title": "Choose a score",
        "download-step-1-text": "Use a PDF, PNG or JPG with clear staff lines and readable notation.",
        "download-step-2-title": "Pick outputs",
        "download-step-2-text": "Start with annotations, then add MP3, MIDI or synchronized video when needed.",
        "download-step-3-title": "Review playback",
        "download-step-3-text": "Use the MIDI player and MP4 preview to inspect timing and note grouping.",
        "doc-install-title": "Install from PyPI",
        "doc-install-text": "Use pip when you want the Python package, command-line entry point and programmatic API.",
        "doc-launch-title": "Launch the app",
        "doc-launch-text": "Open the desktop interface from the terminal or from a Python script.",
        "doc-requirements-title": "External tools",
        "doc-requirements-text": "PDF input uses Poppler. MP3/video exports use FFmpeg. SoundFont rendering uses FluidSynth. The desktop diagnostics panel reports what is available.",
        "doc-output-title": "Output files",
        "doc-output-text": "Depending on the selected options, a run can generate annotations, MP3, MIDI and MP4 files.",
        "guide-kicker": "Interface guide",
        "guide-title": "Desktop processing pipeline",
        "guide-lead": "The desktop flow moves from score selection to progress tracking and result review. The screenshots adapt to the current website theme.",
        "guide-1-title": "Home",
        "guide-1-text": "Start from a focused welcome screen and move into the score workspace when ready.",
        "guide-2-title": "Scores",
        "guide-2-text": "Select PDF or image files, set BPM and choose how much information PyClef should generate.",
        "guide-3-title": "Outputs and presets",
        "guide-3-text": "Use presets for review, listening or video, then fine-tune annotation, audio, MIDI, video and report options.",
        "guide-4-title": "Progress",
        "guide-4-text": "Follow the progress bar and optional technical logs while detection, inference and export run.",
        "guide-5-title": "Results",
        "guide-5-text": "Open the result folder, annotated pages, audio, MIDI, video and scientific report from one place.",
        "guide-6-title": "About",
        "guide-6-text": "Review the project goals, MIRP context and exported result types.",
        "reference-kicker": "Function reference",
        "reference-title": "What each desktop option does.",
        "reference-lead": "PyClef keeps common actions visible and places experimental controls in advanced options.",
        "ref-select-title": "Select scores",
        "ref-select-text": "Loads PDF, PNG, JPG or JPEG files and creates a result folder from the input name.",
        "ref-bpm-title": "BPM",
        "ref-bpm-text": "Defines the tempo used for MIDI, MP3 and synchronized video timing.",
        "ref-presets-title": "Presets",
        "ref-presets-text": "Quickly configures the workflow for review, listening, video sharing or full export.",
        "ref-annotations-title": "Annotated score",
        "ref-annotations-text": "Exports labeled score images. Clean mode groups close notes; detailed mode includes confidence information.",
        "ref-audio-title": "MP3 audio",
        "ref-audio-text": "Renders a listening file using the internal synthesizer or SoundFont piano when available.",
        "ref-midi-title": "MIDI",
        "ref-midi-text": "Exports note events for playback, inspection and use in external music software.",
        "ref-video-title": "Video style",
        "ref-video-text": "Creates score video, piano-roll video or a combined score plus piano-roll review video.",
        "ref-report-title": "Scientific report",
        "ref-report-text": "Summarizes confidence, pitch classes, hand distribution, durations and review recommendations.",
        "ref-advanced-title": "Advanced recognition",
        "ref-advanced-text": "Optional preprocessing and staff-crop recovery can help dense scans while keeping review data visible.",
        "midi-kicker": "MIDI Player",
        "midi-title": "Review generated MIDI files with a piano-roll view.",
        "midi-lead": "The player loads generated MIDI, applies the piano SoundFont and shows timing with a waterfall view and responsive keyboard.",
        "midi-card-1-title": "Waterfall playback",
        "midi-card-1-text": "Notes fall toward the keyboard in sync with playback, making timing problems easier to inspect.",
        "midi-card-2-title": "Dynamic keyboard",
        "midi-card-2-text": "The piano range adapts to the MIDI file and labels white keys with note names.",
        "midi-card-3-title": "Hand-aware colors",
        "midi-card-3-text": "Right-hand and left-hand notes use different colors, including darker tones for black-key notes.",
        "midi-shot-label": "Playback view",
        "midi-shot-text": "Use the player to inspect MIDI timing before sharing or exporting the final result.",
        "midi-secondary-caption": "Loaded MIDI with piano range and metadata.",
        "outputs-kicker": "Generated outputs",
        "outputs-title": "Review the files PyClef actually exports.",
        "outputs-lead": "Each run creates a result folder with annotated pages and the optional playback files selected in the interface.",
        "output-clean-badge": "Annotated score",
        "output-clean-title": "Detected notes on the score",
        "output-clean-text": "The annotated page keeps the original staff visible while adding note names, hand colors and review markers.",
        "output-detailed-badge": "Detailed annotation",
        "output-detailed-title": "Confidence and review cues",
        "output-detailed-text": "Detailed labels expose confidence percentages and mark notes that may deserve a closer manual check.",
        "output-audio-title": "Rendered audio",
        "output-audio-text": "Generate an audio file for listening checks, sharing and quick musical review.",
        "output-video-title": "Score plus piano-roll video",
        "output-video-text": "The synchronized video can combine the active score region with a piano-roll view, making playback easier to study.",
        "api-kicker": "Python API",
        "api-title": "Use PyClef from your own scripts.",
        "api-lead": "The desktop app is the easiest entry point, but the processing engine can also be called programmatically.",
        "api-pyclef-text": "Starts the desktop application from Python.",
        "api-process-text": "Runs the OMR pipeline and returns paths for generated outputs.",
        "api-diagnostics-text": "Checks whether model files, PDF tools, FFmpeg, SoundFont and FluidSynth are available.",
        "usage-kicker": "Recommended use",
        "usage-title": "A simple workflow for repeatable experiments.",
        "usage-1-title": "Prepare the input",
        "usage-1-text": "Use a clear PDF, PNG or JPG. Cleaner scans usually produce better detections.",
        "usage-2-title": "Select outputs",
        "usage-2-text": "Generate annotations first for a quick check. Add audio, MIDI or video as needed.",
        "usage-3-title": "Check annotations",
        "usage-3-text": "Inspect the labeled image to verify note names and structural interpretation.",
        "usage-4-title": "Review playback",
        "usage-4-text": "Use MIDI, MP3 and video to evaluate the reconstructed score.",
        "cite-kicker": "Citation",
        "cite-title": "Citation",
        "cite-text": "If you use PyClef in academic work, cite the project. The MIRP paper will be available soon.",
        "results-kicker": "Evaluation",
        "results-title": "Detection quality and reconstruction quality are reported separately.",
        "results-lead": "PyClef separates object-detection metrics from functional pitch reconstruction metrics, since high mAP does not necessarily imply correct musical reconstruction.",
        "result-map": "YOLOv11S reached 0.4126 mAP@[0.5:0.95] on DeepScoresV2 Dense.",
        "result-tra": "With YOLOv11S, MIRP increased TRA from 0.04 to 0.975.",
        "results-balance-kicker": "Model comparison",
        "results-balance-title": "MIRP reduces the practical gap between model sizes.",
        "results-balance-text": "YOLOv11L reached 0.51379 mAP, but both YOLOv11S and YOLOv11L exceeded 97% TRA after MIRP.",
        "table-kicker": "Summary",
        "table-title": "Reported comparison points.",
        "metric-label": "Metric",
        "pitch-rate": "Pitch Reconstruction Rate",
        "model-size": "Model size",
        "training-cost": "Training cost",
        "smaller": "Smaller",
        "larger": "Larger",
        "lower": "Lower",
        "higher": "Higher",
        "footer-text": "Python toolkit for Optical Music Recognition.",
        "copy-code": "Copy",
        "copied-code": "Copied",
        "lang-btn": "EN"
    },
    pt: {
        "nav-home": "Início",
        "nav-method": "Metodologia",
        "nav-download": "Download",
        "nav-docs": "Docs",
        "nav-results": "Resultados",
        "hero-kicker": "Reconhecimento Óptico de Partituras",
        "hero-title": "Reconhecimento de partituras em Python.",
        "hero-lead": "O PyClef detecta símbolos musicais em imagens de partituras e aplica o MIRP, um método de inferência por referência de pauta, para reconstruir alturas e exportar resultados revisáveis.",
        "hero-start": "Começar",
        "hero-method": "Ler metodologia",
        "metric-classes": "classes de símbolos",
        "metric-pitch": "TRA com MIRP",
        "intro-kicker": "Visão geral",
        "intro-title": "Detecção de objetos, sozinha, não resolve OMR.",
        "intro-text": "O PyClef trata a detecção como uma etapa de um pipeline de reconstrução. O detector localiza símbolos; o MIRP usa a clave detectada e a geometria da pauta para inferir alturas por deslocamento vertical relativo.",
        "card-neural-title": "Modelo de detecção",
        "card-neural-text": "O modelo atual usa YOLOv11S treinado em 208 classes do DeepScoresV2 Dense, com 0,4126 mAP@[0,5:0,95] na avaliação reportada.",
        "card-mirp-title": "MIRP",
        "card-mirp-text": "O Método de Inferência Musical por Referência de Pauta define uma nota de referência pela clave e pela pauta e infere a altura das notas detectadas.",
        "pipeline-kicker": "Fluxo",
        "pipeline-title": "O pipeline de processamento é explícito e verificável.",
        "step-detect-title": "Detectar",
        "step-detect-text": "Carrega PDF ou imagem e detecta pautas, claves, notas, pausas e símbolos relacionados.",
        "step-refine-title": "Inferir",
        "step-refine-text": "Usa o MIRP para converter geometria relativa à pauta em nomes de notas e oitavas.",
        "step-reconstruct-title": "Revisar",
        "step-reconstruct-text": "Cria páginas anotadas para que o resultado do reconhecimento possa ser inspecionado visualmente.",
        "step-export-title": "Exportar",
        "step-export-text": "Gera arquivos MIDI, MP3 e vídeo sincronizado quando essas saídas são selecionadas.",
        "app-kicker": "Aplicação desktop",
        "app-title": "Uma interface focada para executar o PyClef localmente.",
        "app-text": "Selecione uma partitura, escolha as saídas, defina o BPM e execute o pipeline. Os resultados são gravados em uma pasta com o nome do arquivo de entrada.",
        "app-f1": "Entrada PDF, PNG e JPG",
        "app-f2": "Páginas anotadas",
        "app-f3": "MIDI, MP3 e vídeo sincronizado",
        "app-f4": "Player MIDI integrado com visualização em cascata",
        "paper-kicker": "Artigo",
        "paper-title": "Metodologia e avaliação.",
        "paper-text": "O artigo descreve o pipeline do PyClef, o método MIRP e os resultados de detecção e reconstrução de altura reportados.",
        "paper-download": "Coming soon",
        "paper-method": "Metodologia",
        "method-kicker": "Metodologia",
        "method-title": "MIRP: Inferência Musical por Referência de Pauta.",
        "method-lead": "O MIRP usa a clave detectada e os limites da pauta para definir uma nota de referência. As demais notas são inferidas pelo deslocamento vertical em relação a essa referência.",
        "mirp-1-title": "Referência da pauta",
        "mirp-1-text": "A pauta detectada fornece seus limites superior e inferior. O passo vertical é estimado a partir dessas coordenadas.",
        "mirp-2-title": "Referência da clave",
        "mirp-2-text": "A clave determina a nota de referência usada para interpretar posições na pauta.",
        "mirp-3-title": "Reconstrução de altura",
        "mirp-3-text": "No experimento com YOLOv11S, a TRA passou de 0,04 para 0,975 após a aplicação do MIRP.",
        "method-flow-kicker": "Algoritmo",
        "method-flow-title": "O MIRP é aplicado após a detecção de objetos.",
        "flow-1-title": "Coletar detecções",
        "flow-1-text": "Separa detecções estruturais, como pautas e claves, das detecções de notas.",
        "flow-2-title": "Estimar passo da pauta",
        "flow-2-text": "Calcula a distância entre posições adjacentes da pauta a partir da caixa detectada.",
        "flow-3-title": "Inferir altura",
        "flow-3-text": "Mede o deslocamento vertical entre a nota de referência e o centro de cada nota detectada.",
        "flow-4-title": "Exportar resultados",
        "flow-4-text": "Grava imagens anotadas e arquivos opcionais de reprodução para inspeção e reutilização.",
        "article-kicker": "Artigo",
        "article-title": "PyClef: Reconhecimento Óptico de Partituras com MIRP.",
        "article-text": "O artigo reporta resultados com YOLOv11S no DeepScoresV2 Dense e mostra que o MIRP eleva a reconstrução de altura de cerca de 4% para 97,5%.",
        "docs-kicker": "Documentação",
        "docs-title": "Instale o PyClef e execute o fluxo desktop.",
        "docs-lead": "O PyClef pode ser iniciado a partir do Python. A aplicação desktop grava os resultados em uma pasta para inspeção.",
        "doc-install-title": "Instalação",
        "doc-install-text": "Instale o pacote pelo PyPI. No primeiro uso, o PyClef pode baixar o arquivo do modelo automaticamente.",
        "doc-launch-title": "Inicialização",
        "doc-launch-text": "Inicie a interface desktop pelo Python.",
        "doc-output-title": "Arquivos gerados",
        "doc-output-text": "Dependendo das opções selecionadas, uma execução pode gerar anotações, MP3, MIDI e MP4.",
        "guide-kicker": "Guia da interface",
        "guide-title": "Pipeline de processamento desktop",
        "guide-lead": "O fluxo desktop vai da seleção da partitura ao acompanhamento do progresso e à revisão dos resultados. As imagens acompanham o tema atual do site.",
        "guide-1-title": "Home",
        "guide-1-text": "Abra o ambiente de partituras a partir da tela inicial.",
        "guide-2-title": "Partituras",
        "guide-2-text": "Use a página de Partituras para selecionar arquivos, definir BPM e escolher saídas.",
        "guide-3-title": "Opções de saída",
        "guide-3-text": "Escolha anotação, MP3, MIDI, vídeo ou todas as saídas disponíveis.",
        "guide-4-title": "Progresso",
        "guide-4-text": "Acompanhe a barra de progresso e o log enquanto a partitura é processada.",
        "guide-5-title": "Resultados",
        "guide-5-text": "Abra a pasta de resultados ou arquivos individuais após o processamento.",
        "guide-6-title": "Sobre",
        "guide-6-text": "Consulte o resumo do projeto e links na página Sobre.",
        "midi-kicker": "Player MIDI",
        "midi-title": "Revise arquivos MIDI gerados com uma visão tipo piano roll.",
        "midi-lead": "O PyClef agora inclui uma janela dedicada para reprodução MIDI. Ela carrega o MIDI gerado, aplica automaticamente o SoundFont de piano e mostra o tempo das notas com uma visualização em cascata e teclado responsivo.",
        "midi-card-1-title": "Reprodução em cascata",
        "midi-card-1-text": "As notas descem em direção ao teclado de forma sincronizada com a reprodução, facilitando a inspeção de problemas de tempo.",
        "midi-card-2-title": "Teclado dinâmico",
        "midi-card-2-text": "A extensão do piano se adapta ao arquivo MIDI e identifica as teclas brancas com nomes de notas.",
        "midi-card-3-title": "Cores por mão",
        "midi-card-3-text": "Notas da mão direita e da mão esquerda usam cores diferentes, incluindo tons mais escuros para notas em teclas pretas.",
        "midi-shot-label": "Visualização de reprodução",
        "midi-shot-text": "Use o player para inspecionar o tempo do MIDI antes de compartilhar ou exportar o resultado final.",
        "midi-secondary-caption": "MIDI carregado com extensão do piano e metadados.",
        "outputs-kicker": "Arquivos gerados",
        "outputs-title": "Inspecione a partitura como imagem, som, MIDI e vídeo.",
        "outputs-lead": "O PyClef mantém as saídas separadas para que cada resultado seja revisado com o nível de detalhe adequado.",
        "output-clean-badge": "Partitura anotada",
        "output-clean-title": "Visualização limpa",
        "output-clean-text": "Uma sobreposição compacta para conferir rapidamente nomes de notas e agrupamento por pauta.",
        "output-detailed-badge": "Detalhe da anotação",
        "output-detailed-title": "Modo detalhado",
        "output-detailed-text": "A visualização detalhada expande os rótulos com valores de confiança para uma inspeção mais precisa.",
        "output-audio-title": "Áudio renderizado",
        "output-audio-text": "Gere um arquivo de áudio para conferência auditiva, compartilhamento e revisão musical rápida.",
        "output-video-title": "Vídeo sincronizado",
        "output-video-text": "Uma prévia animada e recortada destaca as notas ativas para deixar o MP4 sincronizado mais fácil de entender.",
        "usage-kicker": "Uso recomendado",
        "usage-title": "Um fluxo simples para experimentos reproduzíveis.",
        "usage-1-title": "Prepare a entrada",
        "usage-1-text": "Use um PDF, PNG ou JPG nítido. Digitalizações mais limpas tendem a produzir melhores detecções.",
        "usage-2-title": "Selecione saídas",
        "usage-2-text": "Gere anotações primeiro para uma verificação rápida. Adicione áudio, MIDI ou vídeo quando necessário.",
        "usage-3-title": "Verifique as anotações",
        "usage-3-text": "Inspecione a imagem rotulada para conferir nomes de notas e interpretação estrutural.",
        "usage-4-title": "Revise a reprodução",
        "usage-4-text": "Use MIDI, MP3 e vídeo para avaliar a partitura reconstruída.",
        "cite-kicker": "Citação",
        "cite-title": "Citação",
        "cite-text": "Se usar o PyClef em trabalho acadêmico, cite o projeto. O artigo do MIRP estará disponível em breve.",
        "hero-download": "Baixar Windows",
        "home-download-setup": "Baixar setup",
        "docs-lead": "O PyClef pode ser usado como aplicativo desktop no Windows ou diretamente pelo Python. Este guia cobre instalação, opções de processamento, arquivos gerados, reprodução MIDI e ferramentas de revisão.",
        "docs-download-cta": "Opções de download",
        "docs-python-cta": "Instalar com pip",
        "download-kicker": "Instalador Windows",
        "download-title": "Baixe o setup do PyClef e teste agora no seu computador Windows.",
        "download-text": "Use o setup quando quiser abrir a interface desktop rapidamente e processar uma partitura localmente.",
        "download-button": "Baixar setup",
        "download-release": "Abrir release",
        "download-note": "Recomendado para usuários Windows que querem usar a interface desktop.",
        "download-page-kicker": "Download",
        "download-page-title": "Escolha como você quer executar o PyClef.",
        "download-page-lead": "Use o setup do Windows para testar a interface desktop rapidamente, ou instale o pacote Python quando quiser usar a API e o terminal.",
        "download-windows-kicker": "Setup Windows",
        "download-windows-title": "Baixe o PyClef e teste agora no seu computador Windows.",
        "download-windows-text": "Recomendado se você quer usar a interface desktop sem preparar um ambiente Python primeiro.",
        "download-windows-button": "Baixar setup Windows",
        "download-windows-note": "O instalador é distribuído pelo GitHub Releases porque é um arquivo grande.",
        "download-python-kicker": "Pacote Python",
        "download-python-title": "Instale o PyClef pelo PyPI.",
        "download-python-text": "Use este caminho quando quiser chamar o PyClef por scripts, notebooks ou terminal.",
        "download-python-button": "Abrir guia Python",
        "download-steps-kicker": "Próximos passos",
        "download-steps-title": "Depois da instalação, abra uma partitura e gere suas primeiras saídas.",
        "download-step-1-title": "Escolha uma partitura",
        "download-step-1-text": "Use PDF, PNG ou JPG com pautas nítidas e notação legível.",
        "download-step-2-title": "Escolha as saídas",
        "download-step-2-text": "Comece pelas anotações. Depois adicione MP3, MIDI ou vídeo sincronizado quando precisar.",
        "download-step-3-title": "Revise a reprodução",
        "download-step-3-text": "Use o player MIDI e a prévia MP4 para inspecionar tempo e agrupamento das notas.",
        "doc-install-title": "Instalar pelo PyPI",
        "doc-install-text": "Use pip quando quiser o pacote Python, o comando de terminal e a API programática.",
        "doc-launch-title": "Abrir o app",
        "doc-launch-text": "Inicie a interface desktop pelo terminal ou por um script Python.",
        "doc-requirements-title": "Ferramentas externas",
        "doc-requirements-text": "A entrada em PDF usa Poppler. As exportações MP3 e MP4 usam FFmpeg. A renderização com SoundFont usa FluidSynth. O painel de diagnóstico informa o que está disponível.",
        "doc-output-title": "Arquivos gerados",
        "doc-output-text": "Dependendo das opções selecionadas, uma execução pode gerar anotações, MP3, MIDI e MP4.",
        "guide-kicker": "Guia da interface",
        "guide-title": "Pipeline desktop de processamento",
        "guide-lead": "O fluxo desktop vai da seleção da partitura ao acompanhamento do progresso e à revisão dos resultados. As imagens acompanham o tema atual do site.",
        "guide-1-title": "Home",
        "guide-1-text": "Comece por uma tela inicial direta e entre no ambiente de partituras quando estiver pronto.",
        "guide-2-title": "Partituras",
        "guide-2-text": "Selecione arquivos PDF ou imagem, defina o BPM e escolha quanto o PyClef deve gerar.",
        "guide-3-title": "Saídas e presets",
        "guide-3-text": "Use presets para revisão, escuta, vídeo ou exportação completa. Depois, ajuste anotações, áudio, MIDI, vídeo e relatório.",
        "guide-4-title": "Progresso",
        "guide-4-text": "Acompanhe a barra de progresso e os logs técnicos enquanto detecção, inferência e exportação rodam.",
        "guide-5-title": "Resultados",
        "guide-5-text": "Abra a pasta final, as páginas anotadas, o áudio, o MIDI, o vídeo e o relatório científico em um só lugar.",
        "guide-6-title": "Sobre",
        "guide-6-text": "Consulte os objetivos do projeto, o contexto do MIRP e os tipos de resultado exportados.",
        "reference-kicker": "Referência de funções",
        "reference-title": "O que cada opção da interface faz.",
        "reference-lead": "O PyClef mantém as ações comuns visíveis e deixa controles experimentais nas opções avançadas.",
        "ref-select-title": "Selecionar partituras",
        "ref-select-text": "Carrega PDF, PNG, JPG ou JPEG e cria uma pasta de resultados com base no nome do arquivo.",
        "ref-bpm-title": "BPM",
        "ref-bpm-text": "Define o andamento usado no MIDI, MP3 e vídeo sincronizado.",
        "ref-presets-title": "Presets",
        "ref-presets-text": "Configura rapidamente o fluxo para revisão, escuta, compartilhamento em vídeo ou exportação completa.",
        "ref-annotations-title": "Partitura anotada",
        "ref-annotations-text": "Exporta imagens rotuladas. O modo limpo agrupa notas próximas; o modo detalhado inclui informações de confiança.",
        "ref-audio-title": "Áudio MP3",
        "ref-audio-text": "Renderiza um arquivo de escuta usando o sintetizador interno ou piano com SoundFont quando disponível.",
        "ref-midi-title": "MIDI",
        "ref-midi-text": "Exporta eventos de notas para reprodução, inspeção e uso em softwares musicais externos.",
        "ref-video-title": "Estilo de vídeo",
        "ref-video-text": "Cria vídeo da partitura, vídeo piano-roll ou revisão combinada com partitura e piano-roll.",
        "ref-report-title": "Relatório científico",
        "ref-report-text": "Resume confiança, classes de altura, distribuição por mão, durações e pontos recomendados para revisão.",
        "ref-advanced-title": "Reconhecimento avançado",
        "ref-advanced-text": "Pré-processamento e recuperação por recorte de pauta podem ajudar scans densos mantendo os dados de revisão visíveis.",
        "midi-kicker": "Player MIDI",
        "midi-title": "Revise MIDIs gerados com visualização piano-roll.",
        "midi-lead": "O player carrega o MIDI gerado, aplica o SoundFont de piano e mostra o tempo das notas com visualização em cascata e teclado responsivo.",
        "midi-card-1-title": "Reprodução em cascata",
        "midi-card-1-text": "As notas descem em direção ao teclado em sincronia com a reprodução, facilitando a inspeção do tempo.",
        "midi-card-2-title": "Teclado dinâmico",
        "midi-card-2-text": "A extensão do piano se adapta ao arquivo MIDI e identifica as teclas brancas com nomes de notas.",
        "midi-card-3-title": "Cores por mão",
        "midi-card-3-text": "Notas da mão direita e da mão esquerda usam cores diferentes, incluindo tons mais escuros para teclas pretas.",
        "midi-shot-label": "Visualização de reprodução",
        "midi-shot-text": "Use o player para inspecionar o tempo do MIDI antes de compartilhar ou exportar o resultado final.",
        "midi-secondary-caption": "MIDI carregado com extensão do piano e metadados.",
        "outputs-kicker": "Arquivos gerados",
        "outputs-title": "Revise os arquivos que o PyClef realmente exporta.",
        "outputs-lead": "Cada execução cria uma pasta de resultados com páginas anotadas e os arquivos de reprodução opcionais selecionados na interface.",
        "output-clean-badge": "Partitura anotada",
        "output-clean-title": "Notas detectadas na partitura",
        "output-clean-text": "A página anotada mantém a pauta original visível enquanto adiciona nomes das notas, cores por mão e marcações de revisão.",
        "output-detailed-badge": "Anotação detalhada",
        "output-detailed-title": "Confiança e pistas de revisão",
        "output-detailed-text": "Os rótulos detalhados mostram porcentagens de confiança e marcam notas que podem merecer revisão manual.",
        "output-audio-title": "Áudio renderizado",
        "output-audio-text": "Gere um arquivo de áudio para conferência auditiva, compartilhamento e revisão musical rápida.",
        "output-video-title": "Vídeo com partitura e piano-roll",
        "output-video-text": "O vídeo sincronizado pode combinar a região ativa da partitura com uma visualização piano-roll, facilitando o estudo da reprodução.",
        "api-kicker": "API Python",
        "api-title": "Use o PyClef nos seus próprios scripts.",
        "api-lead": "O aplicativo desktop é a entrada mais simples, mas o motor de processamento também pode ser chamado por código.",
        "api-pyclef-text": "Inicia a aplicação desktop pelo Python.",
        "api-process-text": "Executa o pipeline de OMR e retorna caminhos para os arquivos gerados.",
        "api-diagnostics-text": "Verifica se modelo, ferramentas de PDF, FFmpeg, SoundFont e FluidSynth estão disponíveis.",
        "usage-kicker": "Uso recomendado",
        "usage-title": "Um fluxo simples para experimentos reproduzíveis.",
        "usage-1-title": "Prepare a entrada",
        "usage-1-text": "Use um PDF, PNG ou JPG nítido. Scans mais limpos costumam gerar melhores detecções.",
        "usage-2-title": "Selecione saídas",
        "usage-2-text": "Gere anotações primeiro para uma verificação rápida. Adicione áudio, MIDI ou vídeo quando necessário.",
        "usage-3-title": "Verifique as anotações",
        "usage-3-text": "Inspecione a imagem rotulada para conferir nomes de notas e interpretação estrutural.",
        "usage-4-title": "Revise a reprodução",
        "usage-4-text": "Use MIDI, MP3 e vídeo para avaliar a partitura reconstruída.",
        "cite-kicker": "Citação",
        "cite-title": "Citação",
        "cite-text": "Se usar o PyClef em trabalho acadêmico, cite o projeto. O artigo do MIRP estará disponível em breve.",
        "results-kicker": "Avaliação",
        "results-title": "Qualidade de detecção e qualidade de reconstrução são reportadas separadamente.",
        "results-lead": "O PyClef separa métricas de detecção de objetos das métricas funcionais de reconstrução de altura, pois mAP alto não implica necessariamente reconstrução musical correta.",
        "result-map": "A YOLOv11S alcançou 0,4126 mAP@[0,5:0,95] no DeepScoresV2 Dense.",
        "result-tra": "Com YOLOv11S, o MIRP elevou a TRA de 0,04 para 0,975.",
        "results-balance-kicker": "Comparação de modelos",
        "results-balance-title": "O MIRP reduz a diferença prática entre tamanhos de modelo.",
        "results-balance-text": "A YOLOv11L alcançou 0,51379 mAP, mas tanto a YOLOv11S quanto a YOLOv11L superaram 97% de TRA após o MIRP.",
        "table-kicker": "Resumo",
        "table-title": "Pontos de comparação reportados.",
        "metric-label": "Métrica",
        "pitch-rate": "Taxa de Reconstrução de Altura",
        "model-size": "Tamanho do modelo",
        "training-cost": "Custo de treinamento",
        "smaller": "Menor",
        "larger": "Maior",
        "lower": "Menor",
        "higher": "Maior",
        "footer-text": "Biblioteca Python para Reconhecimento Óptico de Partituras.",
        "copy-code": "Copiar",
        "copied-code": "Copiado",
        "lang-btn": "PT"
    }
};

let currentLang = localStorage.getItem("pyclef-lang") || "en";

function updateTexts() {
    document.documentElement.lang = currentLang;
    document.querySelectorAll("[data-i18n]").forEach((el) => {
        const key = el.getAttribute("data-i18n");
        const value = content[currentLang]?.[key];
        if (value) el.innerHTML = value;
    });
    const langText = document.getElementById("lang-text");
    if (langText) langText.innerText = content[currentLang]["lang-btn"];
}

function setTheme(theme) {
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem("pyclef-theme", theme);
    const icon = document.getElementById("theme-icon");
    if (icon) icon.className = theme === "light" ? "fas fa-sun" : "fas fa-moon";
    document.querySelectorAll(".nav-logo, #main-logo").forEach((logo) => {
        logo.src = theme === "light" ? "imgs/logo_white.png" : "imgs/logo_black.png";
    });
}

document.getElementById("lang-switch")?.addEventListener("click", () => {
    currentLang = currentLang === "en" ? "pt" : "en";
    localStorage.setItem("pyclef-lang", currentLang);
    updateTexts();
});

document.getElementById("theme-switch")?.addEventListener("click", () => {
    const isDark = document.documentElement.getAttribute("data-theme") === "dark";
    setTheme(isDark ? "light" : "dark");
});

const navbar = document.querySelector(".navbar");
const mobileMenuToggle = document.getElementById("mobile-menu-toggle");

mobileMenuToggle?.addEventListener("click", () => {
    const isOpen = navbar?.classList.toggle("nav-open") || false;
    mobileMenuToggle.setAttribute("aria-expanded", String(isOpen));
    const icon = mobileMenuToggle.querySelector("i");
    if (icon) icon.className = isOpen ? "fas fa-xmark" : "fas fa-bars";
});

document.querySelectorAll(".nav-links a").forEach((link) => {
    link.addEventListener("click", () => {
        navbar?.classList.remove("nav-open");
        mobileMenuToggle?.setAttribute("aria-expanded", "false");
        const icon = mobileMenuToggle?.querySelector("i");
        if (icon) icon.className = "fas fa-bars";
    });
});

function copyInstall() {
    const text = document.getElementById("install-command")?.innerText || "pip install pyclef";
    navigator.clipboard.writeText(text).then(() => {
        const icon = document.querySelector(".copy-btn i");
        if (!icon) return;
        icon.className = "fas fa-check";
        icon.style.color = "var(--accent)";
        setTimeout(() => {
            icon.className = "far fa-copy";
            icon.style.color = "";
        }, 1600);
    });
}

document.querySelectorAll(".copy-code-btn").forEach((button) => {
    button.addEventListener("click", () => {
        const code = button.closest(".code-copy-wrap")?.querySelector("code")?.innerText;
        if (!code) return;
        navigator.clipboard.writeText(code).then(() => {
            const original = content[currentLang]["copy-code"];
            button.innerText = content[currentLang]["copied-code"];
            setTimeout(() => {
                button.innerText = original;
            }, 1400);
        });
    });
});

const modal = document.getElementById("imageModal");
const modalImg = document.getElementById("modalImg");

function openModal(img) {
    if (!modal || !modalImg) return;
    modalImg.src = img.src;
    modal.style.display = "flex";
    setTimeout(() => modal.classList.add("active"), 10);
    document.body.style.overflow = "hidden";
}

function closeModal() {
    if (!modal) return;
    modal.classList.remove("active");
    setTimeout(() => {
        modal.style.display = "none";
        document.body.style.overflow = "auto";
    }, 250);
}

setTheme(localStorage.getItem("pyclef-theme") || "dark");
updateTexts();
